/**
 * Central icon registry - only import the icons actually used in the project
 * This dramatically improves build times vs star imports
 */

import { library } from "@fortawesome/fontawesome-svg-core";

// Solid icons
import {
    faArrowDown,
    faArrowRight,
    faArrowUp,
    faArrowUpRightFromSquare,
    faArrowsRotate,
    faAward,
    faBagShopping,
    faBars,
    faBook,
    faBooks,
    faBriefcase,
    faBuilding,
    faCalendarCheck,
    faCalendarClock,
    faCalendarDay,
    faCalendarDays,
    faCalendarPlus,
    faCertificate,
    faChartLine,
    faCheck,
    faChevronDown,
    faChevronRight,
    faChevronUp,
    faCircle,
    faCircleCheck,
    faCircleInfo,
    faCircleXmark,
    faClipboardCheck,
    faClock,
    faCodeBranch,
    faCoins,
    faComments,
    faDisplayChartUp,
    faDoorClosed,
    faDoorOpen,
    faDownload,
    faDragon,
    faEllipsis,
    faEnvelope,
    faEnvelopeCircleCheck,
    faEnvelopeOpenText,
    faEye,
    faFileCircleCheck,
    faFileLines,
    faFingerprint,
    faGavel,
    faHammer,
    faHandHoldingHeart,
    faHandsHelping,
    faHandsHoldingHeart,
    faHandshake,
    faHeart,
    faHeartPulse,
    faHourglass,
    faHouse,
    faImageSlash,
    faInfoCircle,
    faLandmark,
    faLaptop,
    faLightbulb,
    faList,
    faLocationDot,
    faMagnifyingGlass,
    faMagnifyingGlassChart,
    faMap,
    faMessages,
    faMinus,
    faNewspaper,
    faPaperPlane,
    faPartyHorn,
    faPenNib,
    faPenToSquare,
    faPeopleGroup,
    faPhone,
    faQuestion,
    faQuoteLeft,
    faRobot,
    faRocket,
    faShieldHalved,
    faSparkles,
    faSpinner,
    faStar,
    faSterlingSign,
    faStreetView,
    faTable,
    faTag,
    faTriangleExclamation,
    faUniversalAccess,
    faUpRightFromSquare,
    faUser,
    faUserShield,
    faUsers,
    faVideo,
    faXmark,
} from "@awesome.me/kit-0ff725f684/icons/classic/solid";

// Regular icons
import {
    faArrowDown as farArrowDown,
    faArrowRight as farArrowRight,
    faArrowUpRightFromSquare as farArrowUpRightFromSquare,
    faCalendar as farCalendar,
    faCalendarClock as farCalendarClock,
    faCalendarDays as farCalendarDays,
    faCircleCheck as farCircleCheck,
    faCircleQuestion as farCircleQuestion,
    faClock as farClock,
    faClipboardListCheck as farClipboardListCheck,
    faEnvelope as farEnvelope,
    faGlobe as farGlobe,
    faLightbulb as farLightbulb,
    faMessagesQuestion as farMessagesQuestion,
    faPresentationScreen as farPresentationScreen,
    faRoute as farRoute,
    faSparkles as farSparkles,
    faTrophyStar as farTrophyStar,
} from "@awesome.me/kit-0ff725f684/icons/classic/regular";

// Brand icons
import { faLinkedin } from "@awesome.me/kit-0ff725f684/icons/classic/brands";

// Light icons
import {
    faBagShopping as falBagShopping,
    faCheck as falCheck,
    faDisplayChartUp as falDisplayChartUp,
    faHandshake as falHandshake,
    faHeart as falHeart,
    faPenNib as falPenNib,
    faPeopleGroup as falPeopleGroup,
    faRectanglePro as falRectanglePro,
    faTimer as falTimer,
    faUserHeadset as falUserHeadset,
} from "@awesome.me/kit-0ff725f684/icons/classic/light";

// Thin icons
import {
    faLayerGroup as fatLayerGroup,
    faLocationDot as fatLocationDot,
    faSeedling as fatSeedling,
    faSpinner as fatSpinner,
} from "@awesome.me/kit-0ff725f684/icons/classic/thin";

// Sharp solid icons
import {
    faCircleCheck as fassCircleCheck,
    faCircleXmark as fassCircleXmark,
} from "@awesome.me/kit-0ff725f684/icons/sharp/solid";

// Register all icons with the library
library.add(
    // Solid
    faArrowDown,
    faArrowRight,
    faArrowUp,
    faArrowUpRightFromSquare,
    faArrowsRotate,
    faAward,
    faBagShopping,
    faBars,
    faBook,
    faBooks,
    faBriefcase,
    faBuilding,
    faCalendarCheck,
    faCalendarClock,
    faCalendarDay,
    faCalendarDays,
    faCalendarPlus,
    faCertificate,
    faChartLine,
    faCheck,
    faChevronDown,
    faChevronRight,
    faChevronUp,
    faCircle,
    faCircleCheck,
    faCircleInfo,
    faCircleXmark,
    faClipboardCheck,
    faClock,
    faCodeBranch,
    faCoins,
    faComments,
    faDisplayChartUp,
    faDoorClosed,
    faDoorOpen,
    faDownload,
    faDragon,
    faEllipsis,
    faEnvelope,
    faEnvelopeCircleCheck,
    faEnvelopeOpenText,
    faEye,
    faFileCircleCheck,
    faFileLines,
    faFingerprint,
    faGavel,
    faHammer,
    faHandHoldingHeart,
    faHandsHelping,
    faHandsHoldingHeart,
    faHandshake,
    faHeart,
    faHeartPulse,
    faHourglass,
    faHouse,
    faImageSlash,
    faInfoCircle,
    faLandmark,
    faLaptop,
    faLightbulb,
    faList,
    faLocationDot,
    faMagnifyingGlass,
    faMagnifyingGlassChart,
    faMap,
    faMessages,
    faMinus,
    faNewspaper,
    faPaperPlane,
    faPartyHorn,
    faPenNib,
    faPenToSquare,
    faPeopleGroup,
    faPhone,
    faQuestion,
    faQuoteLeft,
    faRobot,
    faRocket,
    faShieldHalved,
    faSparkles,
    faSpinner,
    faStar,
    faSterlingSign,
    faStreetView,
    faTable,
    faTag,
    faTriangleExclamation,
    faUniversalAccess,
    faUpRightFromSquare,
    faUser,
    faUserShield,
    faUsers,
    faVideo,
    faXmark,
    // Regular
    farArrowDown,
    farArrowRight,
    farArrowUpRightFromSquare,
    farCalendar,
    farCalendarClock,
    farCalendarDays,
    farCircleCheck,
    farCircleQuestion,
    farClock,
    farClipboardListCheck,
    farEnvelope,
    farGlobe,
    farLightbulb,
    farMessagesQuestion,
    farPresentationScreen,
    farRoute,
    farSparkles,
    farTrophyStar,
    // Brands
    faLinkedin,
    // Light
    falBagShopping,
    falCheck,
    falDisplayChartUp,
    falHandshake,
    falHeart,
    falPenNib,
    falPeopleGroup,
    falRectanglePro,
    falTimer,
    falUserHeadset,
    // Thin
    fatLayerGroup,
    fatLocationDot,
    fatSeedling,
    fatSpinner,
    // Sharp solid
    fassCircleCheck,
    fassCircleXmark
);

// Export for direct usage
export {
    // Solid
    faArrowDown,
    faArrowRight,
    faArrowUp,
    faArrowUpRightFromSquare,
    faArrowsRotate,
    faAward,
    faBagShopping,
    faBars,
    faBook,
    faBooks,
    faBriefcase,
    faBuilding,
    faCalendarCheck,
    faCalendarClock,
    faCalendarDay,
    faCalendarDays,
    faCalendarPlus,
    faCertificate,
    faChartLine,
    faCheck,
    faChevronDown,
    faChevronRight,
    faChevronUp,
    faCircle,
    faCircleCheck,
    faCircleInfo,
    faCircleXmark,
    faClipboardCheck,
    faClock,
    faCodeBranch,
    faCoins,
    faComments,
    faDisplayChartUp,
    faDoorClosed,
    faDoorOpen,
    faDownload,
    faDragon,
    faEllipsis,
    faEnvelope,
    faEnvelopeCircleCheck,
    faEnvelopeOpenText,
    faEye,
    faFileCircleCheck,
    faFileLines,
    faFingerprint,
    faGavel,
    faHammer,
    faHandHoldingHeart,
    faHandsHelping,
    faHandsHoldingHeart,
    faHandshake,
    faHeart,
    faHeartPulse,
    faHourglass,
    faHouse,
    faImageSlash,
    faInfoCircle,
    faLandmark,
    faLaptop,
    faLightbulb,
    faList,
    faLocationDot,
    faMagnifyingGlass,
    faMagnifyingGlassChart,
    faMap,
    faMessages,
    faMinus,
    faNewspaper,
    faPaperPlane,
    faPartyHorn,
    faPenNib,
    faPenToSquare,
    faPeopleGroup,
    faPhone,
    faQuestion,
    faQuoteLeft,
    faRobot,
    faRocket,
    faShieldHalved,
    faSparkles,
    faSpinner,
    faStar,
    faSterlingSign,
    faStreetView,
    faTable,
    faTag,
    faTriangleExclamation,
    faUniversalAccess,
    faUpRightFromSquare,
    faUser,
    faUserShield,
    faUsers,
    faVideo,
    faXmark,
    // Regular
    farArrowDown,
    farArrowRight,
    farArrowUpRightFromSquare,
    farCalendar,
    farCalendarClock,
    farCalendarDays,
    farCircleCheck,
    farCircleQuestion,
    farClock,
    farClipboardListCheck,
    farEnvelope,
    farGlobe,
    farLightbulb,
    farMessagesQuestion,
    farPresentationScreen,
    farRoute,
    farSparkles,
    farTrophyStar,
    // Brands
    faLinkedin,
    // Light
    falBagShopping,
    falCheck,
    falDisplayChartUp,
    falHandshake,
    falHeart,
    falPenNib,
    falPeopleGroup,
    falRectanglePro,
    falTimer,
    falUserHeadset,
    // Thin
    fatLayerGroup,
    fatLocationDot,
    fatSeedling,
    fatSpinner,
    // Sharp solid
    fassCircleCheck,
    fassCircleXmark,
};
