[[redirects]]
  from = "/mfc"
  to = "https://www.unltd.org.uk/awards/movement-for-change"
  status = 301
  force = true

## This rule redirects to an external API, signing requests with a secret
[[redirects]]
  from = "/ha"
  to = "https://www.unltd.org.uk/awards/healthy-ageing"
  status = 200
  force = true

  ## This rule redirects to an external API, signing requests with a secret
[[redirects]]
  from = "/ate"
  to = "https://www.unltd.org.uk/awards/access-to-employment"
  status = 200
  force = true