name = "unltd"
pages_build_output_dir = "dist"

[vars]
DEV = "true"
DOMAIN = "localhost:8788"
RESEND_FROM_EMAIL = "digital@unltd.org.uk"
FEEDBACK_EMAIL = "tomsheppard@unltd.org.uk"

[env.production.vars]
DEV = "false"
DOMAIN = "unltd.pages.dev"
RESEND_FROM_EMAIL = "digital@unltd.org.uk"
FEEDBACK_EMAIL = "tomsheppard@unltd.org.uk"


[env.preview.vars]
DEV = "false"
DOMAIN = "dev.unltd.pages.dev"
RESEND_FROM_EMAIL = "digital@unltd.org.uk"
FEEDBACK_EMAIL = "tomsheppard@unltd.org.uk"